<?php

namespace ContainerFpCQfKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jw0_PlzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jw0.plz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jw0.plz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'JWTEncoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService', true],
            'advertisement' => ['privates', '.errored..service_locator.jw0.plz.App\\Entity\\Advertisement', NULL, 'Cannot autowire service ".service_locator.jw0.plz": it needs an instance of "App\\Entity\\Advertisement" but this type has been excluded in "config/services.yaml".'],
            'advertisementRepository' => ['privates', 'App\\Repository\\AdvertisementRepository', 'getAdvertisementRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'JWTEncoder' => '?',
            'advertisement' => 'App\\Entity\\Advertisement',
            'advertisementRepository' => 'App\\Repository\\AdvertisementRepository',
            'entityManager' => '?',
        ]);
    }
}
