<?php

namespace ContainerFpCQfKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hw1wvIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hw_1wvI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hw_1wvI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advertisementRepository' => ['privates', 'App\\Repository\\AdvertisementRepository', 'getAdvertisementRepositoryService', true],
        ], [
            'advertisementRepository' => 'App\\Repository\\AdvertisementRepository',
        ]);
    }
}
