<?php

namespace ContainerFpCQfKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertisementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jw0.plz.App\Entity\Advertisement' shared service.
     *
     * @return \App\Entity\Advertisement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jw0.plz": it needs an instance of "App\\Entity\\Advertisement" but this type has been excluded in "config/services.yaml".');
    }
}
