<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpCQfKM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpCQfKM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpCQfKM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpCQfKM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFpCQfKM\App_KernelDevDebugContainer([
    'container.build_hash' => 'FpCQfKM',
    'container.build_id' => '7104c913',
    'container.build_time' => 1760904660,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpCQfKM');
